import { DASHBOARD_I18N } from "./dashboardTranslate.js";

export const MORE_I18N = {
  en: {
    ...DASHBOARD_I18N.en,
    biometric: "Fingerprint unlock",
    bioOn: "On",
    bioOff: "Off",
    bioUnsupported: "Android app only",
    bioUnsupportedHint:
      "Fingerprint unlock needs the EazyCount Android app. In a browser, use “Remember me” instead.",
    bioEnabledHint: "Opens with your fingerprint",
    bioDisabledHint:
      "Turn on to open EazyCount with your fingerprint instead of typing the password.",
    bioManage: "Manage",
    bioEnableFailed: "Could not enable fingerprint unlock.",
    bioDeviceLimit: "Too many devices. Revoke one first.",
    loginDevices: "Login devices",
    more: "More",
    moreSubtitle: "Tools and settings",
    report: "Report",
    reportDescription: "View financial and operational reports.",
    userManagement: "Admin",
    userManagementDescription: "Manage users, roles and permissions.",
    domain: "Domain",
    domainDescription: "C168 domain list, fees and renewals.",
    announcement: "Announcement",
    announcementDescription: "Create, edit and delete announcements.",
    autoRenew: "Auto Renew",
    autoRenewDescription: "Approve company and group renewals.",
    ownership: "Ownership",
    ownershipDescription: "Set company and group ownership percentages.",
    settings: "Settings",
    settingsDescription: "Profile, language, appearance and logout.",
    appearance: "Appearance",
    themeLight: "Light",
    themeDark: "Dark",
    back: "Back",
    noTools: "No additional tools are available for your account.",
    open: "Open",
  },
  zh: {
    ...DASHBOARD_I18N.zh,
    biometric: "指纹解锁",
    bioOn: "已开启",
    bioOff: "已关闭",
    bioUnsupported: "仅安卓 App 可用",
    bioUnsupportedHint: "指纹解锁需要 EazyCount 安卓 App。在浏览器里请改用「记住我」。",
    bioEnabledHint: "打开 App 时用指纹直接进入",
    bioDisabledHint: "开启后打开 App 用指纹直接进入，不必输密码。",
    bioManage: "管理",
    bioEnableFailed: "开启指纹解锁失败。",
    bioDeviceLimit: "设备数已达上限，请先下线一台。",
    loginDevices: "我的登录设备",
    more: "更多",
    moreSubtitle: "工具与设置",
    report: "报表",
    reportDescription: "查看财务与营运报表。",
    userManagement: "管理",
    userManagementDescription: "管理用户、角色与权限。",
    domain: "Domain",
    domainDescription: "C168 Domain 列表、费用与续期。",
    announcement: "公告",
    announcementDescription: "创建、编辑与删除公告。",
    autoRenew: "自动续费",
    autoRenewDescription: "审批公司与集团续费申请。",
    ownership: "Ownership",
    ownershipDescription: "设置公司与分组的归属比例。",
    settings: "设置",
    settingsDescription: "资料、语言、外观与退出登录。",
    appearance: "外观",
    themeLight: "浅色",
    themeDark: "深色",
    back: "返回",
    noTools: "你的账户暂无其他可用工具。",
    open: "打开",
  },
};
